export const SETADJUST = "SETADJUST"
export const SETPAYMENT = "SETPAYMENT"
export const DELETEADJUST = 'DELETEADJUST'
export const DELETEPAYMENT = 'DELETEPAYMENT'
export const UPDATEPAYMENT = 'UPDATEPAYMENT'
export const UPDATEADJUST = 'UPDATEADJUST'
export const SETADJUSTFROMRESP = "SETADJUSTFROMRESP"
export const SETPAYMENTRESP = "SETPAYMENTRESP"
export const RESETRESP = "RESETRESP"
export const SETRADIOVALUE = "SETRADIOVALUE"

export const LOADER = "LOADER"
export const SELLERDEFAULTS = "SELLERDEFAULTS"
export const SALESDEFAULTS = "SALESDEFAULTS"
export const SETSELLER = "SETSELLER"
export const SETSALESREP = "SETSALESREP"
export const SETSELLERCOMMSETTINGID = "SETSELLERCOMMSETTINGID"
export const SETSALESCOMMSETTINGID = "SETSALESCOMMSETTINGID"

export const SELLERSAVED = "SELLERSAVED"
export const SALESRSAVED = "SALESRSAVED"
export const SETSELLERLOTS = "SETSELLERLOTS"
export const SETSALESLOTS = "SETSALESLOTS"
export const RESETINTIAL = "RESETINTIAL"

export const SETSELLERADJUST = "SETSELLERADJUST"
export const SETSELLERADJUSTFROMRESP = "SETSELLERADJUSTFROMRESP"
export const DELETESELLERADJUST = 'DELETESELLERADJUST'
export const UPDATESELLERADJUST = 'UPDATESELLERADJUST'
export const SETSELLERPAYMENT = "SETSELLERPAYMENT"
export const SETSELLERPAYMENTRESP = "SETSELLERPAYMENTRESP"
export const SETSELLERRADIOVALUE = "SETSELLERRADIOVALUE"
export const DELETESELLERPAYMENT = 'DELETESELLERPAYMENT'
export const UPDATESELLERPAYMENT = 'UPDATESELLERPAYMENT'
export const RESETSELLER = "RESETSELLER"

export const ADDLOGNOTE = 'ADDLOGNOTE'
export const UPDATELOGNOTE = 'UPDATELOGNOTE'
export const DELETELOGNOTE = 'DELETELOGNOTE'

export const CUSTOMERCONTACTINFO = "CUSTOMERCONTACTINFO"
export const CUSTOMERINTEREST = "CUSTOMERINTEREST"
export const RESETCUSTOMER = "RESETCUSTOMER"

export const ACTIVESTEP = "ACTIVESTEP"
export const AUCTIONNFOACTIVE = "AUCTIONNFOACTIVE"
export const AUCTIONID = "AUCTIONID"
export const AUCTIONINFO = "AUCTIONINFO"
export const RESETAUCTION = "RESETAUCTION"
